<?php
// product_data.php

$products = [
    1 => [
        'id' => 1,
        'name' => 'Vivo X200 Pro 5G (Cosmos Black, 512 GB)  (16 GB RAM)',
        'image' => 'Product_images/vivox200.png',
        'image2' => 'Product_images/vivox200.2.png',
        'description' => 'A powerful smartphone with professional camera features.',
        'price' => '94999'
    ],
    2 => [
        'id' => 2,
        'name' => 'SAMSUNG Galaxy S25 Ultra 5G (Titanium Black, 512 GB)  (12 GB RAM)',
        'image' => 'Product_images/galaxys25.png',
        'image2' => 'Product_images/galaxys25.2.png',
        'description' => 'Premium smartphone with AMOLED display.',
        'price' => '141999'
    ],
    3 => [
                        'id' => 3,
                        'name' => 'Google Pixel 9 Pro 5G (Hazel Grey, 256 GB)  (16 GB RAM)',
                        'image' => 'Product_images/pixel9.png',
                        'description' => 'Best camera phone with pure Android experience.',
                        'price' => '99999',
                        'image2' => 'Product_images/pixel9.2.png',
                    ],
                    4 =>[
                        'id' => 4,
                        'name' => 'OnePlus 13 5G (Arctic Dawn, 512 GB ROM)  (16 GB RAM)',
                        'image' => 'Product_images/oneplus13.png',
                        'description' => 'Flagship killer with fast charging.',
                        'price' => '73990',
                        'image2' => 'Product_images/oneplus13.2.png',
                    ],
                5 =>    [
                        'id' => 5,
                        'name' => 'Apple iPhone 16 Pro Max 5G (Desert Titanium, 256 GB)    ',
                        'image' => 'Product_images/iphone16.png',
                        'description' => 'Apple\'s latest with A16 Bionic chip.',
                        'price' => '135900',
                        'image2' => 'Product_images/iphone16.2.png',
                    ],
                6 =>    [
                        'id' => 6,
                        'name' => 'Nothing Phone (3a) 5G (Black, 256 GB ROM)  (8 GB RAM)',
                        'image' => 'Product_images/nothing3a.png',
                        'description' => 'Budget phone with great performance.',
                        'price' => '26999',
                        'image2' => 'Product_images/nothing3a.2.png',
                    ],
                7 =>    [
                        'id' => 7,
                        'name' => 'ROG Phone 8 Pro Edition (Phantom Black,1 TB) (24 GB)',
                        'image' => 'Product_images/rog8.png',
                        'description' => 'Gaming smartphone with 165Hz refresh rate LTPO Display.',
                        'price' => '119999',
                        'image2' => 'Product_images/rog8.2.png',
                    ],
                8 =>    [
                        'id' => 8,
                        'name' => 'Xiaomi 14 Ultra 5G (White, 512 GB ROM)  (16 GB RAM) ',
                        'image' => 'Product_images/xiaomi14.png',
                        'description' => '4K OLED display with professional camera features.',
                        'price' => '99999',
                        'image2' => 'Product_images/xiaomi14.2.png',
                    ],
                9 =>    [
                        'id' => 9,
                        'name' => 'MOTOROLA Edge 60 Fusion 5G (PANTONE Zephyr, 256 GB)  (12 GB RAM)',
                        'image' => 'Product_images/moto60.png',
                        'description' => 'Budget phone with all latest features.',
                        'price' => '24999',
                        'image2' => 'Product_images/moto60.2.png',
                    ],
                10 =>    [
                        'id' => 10,
                        'name' => 'OPPO Find X8 Pro 5G (Space Black, 512 GB)  (16 GB RAM)',
                        'image' => 'Product_images/oppox8.png',
                        'description' => 'Premium phone with greate camera and performance.',
                        'price' => '99999',
                        'image2' => 'Product_images/oppox8.2.png',
                ],
    11 => [
        'id' => 11,
        'name' => 'Google Pixel Buds Pro with Active Noise Cancellation Bluetooth  (Bay, True Wireless)',
        'image' => 'Product_images/pixelbuds.png',
        'image2' => 'Product_images/pixelbuds.png',
        'description' => 'Experience sound like never before.',
        'price' => '9990'
    ],
                    [
                        'id' => 12,
                        'name' => 'OnePlus Z2-R Active Noise Cancellation Bluetooth  (Red, In the Ear)',
                        'image' => 'Product_images/oppoheadphone.png',
                        'description' => 'Premium ANC for immersive listening.',
                        'price' => '1884',
                        'image2' => 'Product_images/oppoheadphone.png',
                    ],
                    [
                        'id' => 13,
                        'name' => 'boAt Stone 350 Pro with Dynamic RGB LEDs (Raging Black, Mono Channel)',
                        'image' => 'Product_images/noisespeaker.png',
                        'description' => 'Portable speaker with 12hr battery life.',
                        'price' => '1699',
                        'image2' => 'Product_images/noisespeaker.png.png',
                    ],
                    [
                        'id' => 14,
                        'name' => 'Boult 70 Hrs Battery, Eelctronic Noise Cancellation Mic (Black, On the Ear)',
                        'image' => 'Product_images/boult.png',
                        'description' => 'Professional-grade audio for creators.',
                        'price' => '1999',
                        'image2' => 'Product_images/boult.png',
                    ],
                    [
                        'id' => 15,
                        'name' => 'Panasonic SC-HT460GW-K 100 W Bluetooth Home Theatre  (Black, 4.1 Channel)',
                        'image' => 'Product_images/panasonic.png',
                        'description' => 'Home theater experience with wireless subwoofer.',
                        'price' => '5999',
                        'image2' => 'Product_images/panasonic.png',
                    ],
                    [
                        'id' => 16,
                        'name' => 'CMF by Nothing Buds 42 dB Active Noise Cancellation (Orange, True Wireless)',
                        'image' => 'Product_images/nothingbuds.png',
                        'description' => 'Compact earbuds with 6hr battery life.',
                        'price' => '2299',
                      'image2' => 'Product_images/nothingbuds.png',
                    ],
                    [
                        'id' => 17,
                        'name' => 'SpinBot Headphones with 50ms Low Latency (Black, On the Ear)',
                        'image' => 'Product_images/gaminghaedphone.png',
                        'description' => '7.1 surround sound with mic.',
                        'price' => '1851',
                        'image2' => 'Product_images/gaminghaedphone.png',
                    ],
                    [
                        'id' => 18,
                        'name' => 'Octec Digital to Analog Audio Converter, Coaxial/Toslink to RCA (L/R) 5V (Black)',
                        'image' => 'Product_images/dac.png',
                        'description' => 'High-resolution audio on the go.',
                        'price' => '693',
                        'image2' => 'Product_images/dac.png',
                    ],
                    [
                        'id' => 19,
                        'name' => 'realme Buds Wireless 3 Neo with 13.4mm Driver (Black, In the Ear)',
                        'image' => 'Product_images/realmeneckband.png',
                        'description' => 'Comfortable around-neck design.',
                        'price' => '1099',
                        'image2' => 'Product_images/realmeneckband.png',
                    ],
                    [
                        'id' => 20,
                        'name' => 'SONY SRS-XB100 Portable Super-Compact, 16Hrs Battery (Grey, Stereo Channel)',
                        'image' => 'Product_images/sonyspeaker.png',
                        'description' => 'Bookshelf speakers with amazing clarity.',
                        'price' => '4499',
                        'image2' => 'Product_images/sonyspeaker.png',
                    ],
                    [
                        'id' => 21,
                        'name' => 'SAMSUNG 108 cm (43 inch) Ultra HD (4K) LED Smart Tizen TV  (UA43TU8570UXXL)',
                        'image' => 'Product_images/samsung108.png',
                        'description' => 'Ultra HD resolution for a premium viewing experience.',
                        'price' => '67999',
                        'image2' => 'Product_images/samsung108.png',
                    ],
                    [
                        'id' => 22,
                        'name' => 'SAMSUNG 163 cm (65 inch) Ultra HD (4K) Neo QLED Smart Tizen TV  (QA65QN85CAKLXL)',
                        'image' => 'Product_images/samsung163.png',
                        'description' => 'Future-proof with stunning picture quality.',
                        'price' => '154999',
                        'image2' => 'Product_images/samsung163.png',
                    ],
                    [
                        'id' => 23,
                        'name' => 'LG UltraGear 81.28 cm (32 inch) Curved Quad HD LED Backlit VA Panel with 1000R Curvature',
                        'image' => 'Product_images/lgcurved.png',
                        'description' => '1ms response time for competitive gaming.',
                        'price' => '25999',
                        'image2' => 'Product_images/lgcurved.png',
                    ],
                    [
                        'id' => 24,
                        'name' => 'Acer Nitro ED0 80.01 cm (31.5 inch) Curved Full HD LED Backlit VA Panel with 1500R Curvature ',
                        'image' => 'Product_images/acercurved.png',
                        'description' => 'Immersive 34" display for productivity.',
                        'price' => '19999',
                        'image2' => 'Product_images/acercurved.png',
                    ],
                    [
                        'id' => 25,
                        'name' => 'Bestor HY300 Pro Smart Projector, 160 ANSI Lumens, 720P, 4K Support, 180° Rotation. (160 lm) Portable Projector  (White)',
                        'image' => 'Product_images/projecter.png',
                        'description' => '100" screen anywhere with 1080p resolution.',
                        'price' => '5599',
                        'image2' => 'Product_images/projecter.png',
                    ],
                    [
                        'id' => 26,
                        'name' => 'Lenovo 68.58 cm (27 inch) Curved Full HD VA Panel 99% sRGB, 90% DCI-P3, 2x3W Inbuilt Speakers',
                        'image' => 'Product_images/legioncurved.png',
                        'description' => 'Professional color accuracy for creators.',
                        'price' => '16599',
                        'image2' => 'Product_images/legioncurved.png',
                    ],
                    [
                        'id' => 27,
                        'name' => 'Sansui 109 cm (43 inch) Full HD LED Smart Google TV with Panel HDR10 Audio  (JSW43GSFHD)"',
                        'image' => 'Product_images/sansui.png  ',
                        'description' => 'Brighter than OLED with quantum dot technology.',
                        'price' => '25999',
                        'image2' => 'Product_images/sansui.png',
                    ],
                    [
                        'id' => 28,
                        'name' => 'ViewSonic 40.64 cm (16 inch) Full HD LED Backlit TN Panel Touch compatible, ergonomic design Monitor',
                        'image' => 'Product_images/viewsonic.png   ',
                        'description' => 'Interactive 27" display for creative work.',
                        'price' => '26999',
                        'image2' => 'Product_images/viewsonic.png',
                    ],
                    [
                        'id' => 29,
                        'name' => 'TCL C755 215 cm (85 inch) Ultra HD (4K) Mini LED Smart Google TV with 144Hz VRR and IMAX Enhanced  (85C755)',
                        'image' => 'Product_images/tcl.png',
                        'description' => 'Thousands of dimming zones for perfect contrast.',
                        'price' => '259999  ',
                        'image2' => 'Product_images/tcl.png',
                    ],
                    [
                        'id' => 30,
                        'name' => 'TCL P655 139 cm (55 inch) Ultra HD (4K) LED Smart Google TV with T-Screen, Dynamic Colour Enhancement and Dolby Audio 24W  (55P655)',
                        'image' => 'Product_images/tcl55.png',
                        'description' => 'Weatherproof design with anti-glare screen.',
                        'price' => '29590',
                        'image2' => 'Product_images/tcl55.png',
                    ],
                    [
                        'id' => 31,
                        'name' => 'SAMSUNG Galaxy Book5 Pro 360 AI PC Full Metal Chasis Intel Core Ultra 7 258V - (32 GB/1 TB SSD/Windows 11 Home) NP960QHA 2 in 1 Laptop',
                        'image' => 'Product_images/galaxybook.png',
                        'description' => 'Thin and light with all-day battery.',
                        'price' => '195999',
                        'image2' => 'Product_images/galaxybook.png',
                    ],
                    [
                        'id' => 32,
                        'name' => 'ASUS ROG Zephyrus G16 (2025) with Office 2024 + M365 Basic* Intel Core Ultra 9 285H - (32 GB/2 TB SSD/Windows 11 Home/16 GB Graphics/NVIDIA GeForce RTX 5080',
                        'image' => 'Product_images/roggaming.png',
                        'description' => 'RTX 5080 for maximum performance.',
                        'price' => '349999',
                        'image2' => 'Product_images/roggaming.png',
                    ],
                    [
                        'id' => 33,
                        'name' => 'Lenovo IdeaPad Flex 5 AMD Ryzen 5 Hexa Core 7530U - (16 GB/512 GB SSD/Windows 11 Home) 14ABR8 2 in 1 Laptop',
                        'image' => 'Product_images/lennova.png',
                        'description' => 'Laptop and tablet in one device.',
                        'price' => '60599',
                        'image2' => 'Product_images/lennova.png',
                    ],
                    [
                        'id' => 34,
                        'name' => 'Apple MacBook AIR Apple M2 - (16 GB/256 GB SSD/macOS Sequoia) MC7X4HN/A  (13.6 Inch, Midnight, 1.24 kg)',
                        'image' => 'Product_images/macm2.png',
                        'description' => 'Apple silicon with fanless design.',
                        'price' => '75999',
                        'image2' => 'Product_images/macm2.png',
                    ],
                    [
                        'id' => 35,
                        'name' => 'Lenovo Lenovo V15 G3 IAP Intel Core i7 12th Gen 1255U - (16 GB/512 GB SSD/Windows 11 Home) 82TTA073IN Thin and Light Laptop ',
                        'image' => 'Product_images/lennovav15.png',
                        'description' => 'For professionals who need power.',
                        'price' => '50999',
                        'image2' => 'Product_images/lennovav15.png',
                    ],
                    [
                        'id' => 36,
                        'name' => 'MOTOROLA Motobook 60 Full Metal Intel Core 5 (Series 2) 210H - (16 GB/512 GB SSD/Windows 11 Home) 14IRH10R Thin and Light Laptop',
                        'image' => 'Product_images/motolaptop.png',
                        'description' => 'Great for students and everyday use.',
                        'price' => '65999   ',
                        'image2' => 'Product_images/motolaptop.png',
                    ],
                    [
                        'id' => 37,
                        'name' => 'HP Chromebook MediaTek Kompanio 500 - (4 GB/64 GB EMMC Storage/Chrome OS) 11a-na0006MU Chromebook',
                        'image' => 'Product_images/hp.png',
                        'description' => 'Simple and secure for web browsing.',
                        'price' => '18999',
                        'image2' => 'Product_images/hp.png',
                    ],
                    [
                        'id' => 38,
                        'name' => 'MSI Modern 14 Intel Core i3 12th Gen 1215U - (8 GB/512 GB SSD/Windows 11 Home) Modern 14 C12MO Business Laptop',
                        'image' => 'Product_images/msi.png',
                        'description' => 'Enterprise-grade security features.',
                        'price' => '32999',
                        'image2' => 'Product_images/msi.png',
                    ],
                    [
                        'id' => 39,
                        'name' => 'HP Professional Intel Core i5 13th Gen 1334U Turbo Boost Finger Print - (32 GB/512 GB SSD/Windows 11 Pro) 250 G10 Thin and Light Laptop',
                        'image' => 'Product_images/hppro.png',
                        'description' => 'Optimized for video editing and design.',
                        'price' => '62999',
                        'image2' => 'Product_images/hppro.png',
                    ],
                    [
                        'id' => 40,
                        'name' => 'ASUS TUF Gaming A15 AMD Ryzen 5 Hexa Core 7535HS - (8 GB/512 GB SSD/Windows 11 Pro/4 GB Graphics/NVIDIA GeForce RTX 2050) FA506NF-HN578W Gaming Laptop',
                        'image' => 'Product_images/asustuf.png',
                        'description' => 'Military-grade durability.',
                        'price' => '61999',
                        'image2' => 'Product_images/asustuf.png',
                    ]
];